### ISSUE TITLE
Omnifocus plugin doesn't create any journal entries...

### ISSUE THREAD

**Issue by ghost** [ttscoff/Slogger#226]
I have a lot of tasks completed in omnifocus, but when i launch ./slogger, no entries are created in day one. The plugin seems starting well ('OmniFocusLogger: Logging OmniFocus for completed tasks') but that's all :-s. It's like, it found nothing to import in DO...

Others plugins work correctly (i use twitter, feed, blog) 

If someone have a solution, that will be greatly appreciated ^^

i'm running OS X 10.9, and i tried with all the common versions of Ruby. (1.8.x - 1.9.x - 2.x)

Thank you for your help !

**Comment by emory** [comment]
I'd like to re-open this issue because I believe it is still not working as expected in the `master` branch. 

In order to get the plugin to create entries, I have to request `-t` days or it will never log a completed item.

When I do run with `-t` days, it does not update the date last run in the config, is that an important observation?
